<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260129102437 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE visitor_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visited_on TIMESTAMP(0) WITH TIME ZONE NOT NULL, ip_truncated VARCHAR(255) DEFAULT NULL, ip_hash TEXT DEFAULT NULL, method VARCHAR(10) NOT NULL, host TEXT DEFAULT NULL, path TEXT NOT NULL, route TEXT DEFAULT NULL, query_string TEXT DEFAULT NULL, user_agent TEXT DEFAULT NULL, referre TEXT DEFAULT NULL, accept_language TEXT DEFAULT NULL, dnt BOOLEAN DEFAULT NULL, country_iso VARCHAR(2) DEFAULT NULL, region_name TEXT DEFAULT NULL, city_name TEXT DEFAULT NULL, timezone TEXT DEFAULT NULL, asn INT DEFAULT NULL, as_org TEXT DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE visitor_log');
    }
}
